### ISSUE TITLE
用到JSONObject字段作为提交查询时的异常

### ISSUE THREAD

**Issue by xiaotong2019** [JDK-Plus/spring-boot-starter-milvus#23]
你好，很高兴用到你的这个开源source。但我testing过程中，遇到一个嵌套查询异常？

1, source code:
LambdaQueryWrapper<UserBlogVector> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(UserBlogVector::getUserId, 2656274875L)
                .or()
                .ne(UserBlogVector::getUserId, 1234567890L)
                    //下面json查询，运行时提示递归更新异常？
                .or(jsonWrapper ->
                        jsonWrapper
                                .jsonContains(UserBlogVector::getBlogType, 1, "type")
//                                .jsonContainsAll(UserBlogVector::getBlogType, Arrays.asList("1", "2"), "type")
//                                .or()
//                                .jsonContainsAny(UserBlogVector::getBlogType, Arrays.asList("112", "312"), "tasd")
                );

        List<UserBlogVector> results = userBlogVectorRpt.query(wrapper);

env: jdk17,springboot3.2,milvus 3.2.x

2, exception:
java.lang.IllegalStateException: Recursive update

	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1063)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at plus.jdk.milvus.toolkit.LambdaUtils.installCache(LambdaUtils.java:83)
	at plus.jdk.milvus.metadata.CollectionHelper.initCollectionInfo(CollectionHelper.java:115)
	at plus.jdk.milvus.metadata.CollectionHelper.getCollectionInfo(CollectionHelper.java:63)
	at plus.jdk.milvus.toolkit.LambdaUtils.lambda$getColumnMap$1(LambdaUtils.java:116)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at plus.jdk.milvus.toolkit.CollectionUtils.computeIfAbsent(CollectionUtils.java:102)
	at plus.jdk.milvus.toolkit.LambdaUtils.getColumnMap(LambdaUtils.java:115)
	at plus.jdk.milvus.conditions.AbstractLambdaWrapper.tryInitCache(AbstractLambdaWrapper.java:50)
	at plus.jdk.milvus.conditions.AbstractLambdaWrapper.getColumnCache(AbstractLambdaWrapper.java:41)
	at plus.jdk.milvus.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:24)
	at plus.jdk.milvus.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:16)
	at plus.jdk.milvus.conditions.AbstractWrapper.lambda$jsonContains$7(AbstractWrapper.java:190)
	at plus.jdk.milvus.conditions.AbstractWrapper.maybeDo(AbstractWrapper.java:359)
	at plus.jdk.milvus.conditions.AbstractWrapper.jsonContains(AbstractWrapper.java:190)
	at plus.jdk.milvus.conditions.AbstractWrapper.jsonContains(AbstractWrapper.java:39)
	at plus.jdk.milvus.conditions.interfaces.Func.jsonContains(Func.java:181)

**Comment by 1402564807** [comment]
你好，争取在下个版本解决这个问题，顺便说一下，在解决这个问题之前可以使用wrapper.apply(...)来自定义过滤表达式来达到目的
