### ISSUE TITLE
This tool does not support Webflux, spring mvc `WebMvcConfigurer` class is needed, 

### ISSUE THREAD

**Issue by Jovons** [JDK-Plus/spring-boot-starter-milvus#3]
This tool does not support webflux. For now, spring mvc is needed. Otherwise, it causes error at startup:
```
java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurer
```
A more concret error stack is like this:
```
ERROR [main] org.springframework.boot.SpringApplication - TID:N/A - Application run failed
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getDeclaredAnnotations(Class.java:3477)
	at org.springframework.core.annotation.AnnotationsScanner.getDeclaredAnnotations(AnnotationsScanner.java:454)
	at org.springframework.core.annotation.AnnotationTypeMappings.addMetaAnnotationsToQueue(AnnotationTypeMappings.java:84)
	at org.springframework.core.annotation.AnnotationTypeMappings.addAllMappings(AnnotationTypeMappings.java:79)
	at org.springframework.core.annotation.AnnotationTypeMappings.<init>(AnnotationTypeMappings.java:68)
```

**Comment by Jovons** [comment]
It is `AnnotationConfigReactiveWebServerApplicationContext` injected not `WebApplicationObjectSupport`

**Comment by Jovons** [comment]
Perhaps like this `git show` output, so it works with `webflux` as well.
1. pom.xml
```
-        <dependency>
-            <groupId>org.springframework.boot</groupId>
-            <artifactId>spring-boot-starter-web</artifactId>
-            <exclusions>
-                <exclusion>
-                    <groupId>org.springframework.boot</groupId>
-                    <artifactId>spring-boot-starter-tomcat</artifactId>
-                </exclusion>
-            </exclusions>
-        </dependency>
```

2. MIlvusSelector.java:
```
 import org.springframework.beans.factory.BeanFactoryAware;
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.Configuration;
-import org.springframework.web.context.support.WebApplicationObjectSupport;
-import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
+import org.springframework.context.ApplicationContext;
 import plus.jdk.milvus.config.MilvusPlusProperties;
 import plus.jdk.milvus.global.TypeHandlerRegistry;
 import plus.jdk.milvus.global.handler.UnknownTypeHandler;
 import plus.jdk.milvus.global.MilvusClientService;
 
 @Configuration
-public class MilvusSelector extends WebApplicationObjectSupport implements BeanFactoryAware, WebMvcConfigurer {
+public class MilvusSelector  implements BeanFactoryAware {
 
     public static BeanFactory beanFactory;
 
@@ -28,12 +27,12 @@ public class MilvusSelector extends WebApplicationObjectSupport implements BeanF
     }
 
     @Bean
-    public MilvusClientService getMilvusClientService(MilvusPlusProperties properties) {
-        return new MilvusClientService(properties, beanFactory, getApplicationContext());
+    public MilvusClientService getMilvusClientService(MilvusPlusProperties properties, ApplicationContext ctx) {
+        return new MilvusClientService(properties, beanFactory,ctx);
     }
 
     @Bean
-    public TypeHandlerRegistry TypeHandlerRegistry(MilvusPlusProperties properties) {
-        return new TypeHandlerRegistry(properties, beanFactory, getApplicationContext());
+    public TypeHandlerRegistry TypeHandlerRegistry(MilvusPlusProperties properties, ApplicationContext ctx) {
+        return new TypeHandlerRegistry(properties, beanFactory, ctx);
     }
 }
```

**Comment by p-moon** [comment]
Hello there! First and foremost, I want to express my sincere gratitude for bringing this feature request to my attention and showing interest in my project. I need to be upfront about my current situation, as I find myself swamped with work commitments, making it difficult for me to dedicate time to address this specific request. However, I truly appreciate your enthusiasm and willingness to contribute.

I'd like to propose an alternative course of action. If you're willing, you could attempt to make the necessary modifications to this feature on your own and then thoroughly test it to ensure it functions correctly. Once you're confident that everything is working as intended, I strongly encourage you to initiate a pull request, submitting your changes to me. This will not only be a significant step toward improving and enriching the project but also a collaborative effort to create a better software experience for a broader audience.

Once again, thank you for your support and understanding. I look forward to seeing your contribution. Let's work together to make this project even more outstanding!


你好！首先，非常感谢你提出这个需求并对我的项目感兴趣。我要坦诚地告诉你，目前我正陷入繁忙的工作中，难以抽出时间来满足这个需求。然而，我非常欣赏你的热情和贡献意愿。

我想提出一个建议，如果你愿意的话，可以尝试自行修改这个功能，然后进行测试确保它正常运作。一旦你确认一切都运行良好，我鼓励你发起一个合并请求（Merge Request），将你的修改提交给我。这将有助于我们一起改进并丰富这个软件项目，为更多人创造更好的体验。

再次感谢你的支持和理解，期待看到你的贡献。一起努力，让这个项目变得更加出色！
